# -*- coding: utf-8 -*-
"""다중회귀.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XS6KyY5jM73XntRLtwHuIfZf_0X3_QH2
"""

import pandas  as pd
# 데이터 프레임 ( 넘파이 배열과 다르게 타입이 다른 데이터를 섞어서 가져올 수 있다.)
df = pd.read_csv('https://bit.ly/perch_csv')
print(f'데이터 프레임 배열 \n{df}\n')

perch_full = df.to_numpy()
print(f'넘파이 배열 \n{perch_full}')

#                                 변환기(특성 변환)          LinearRgression 추청기
from sklearn.preprocessing import PolynomialFeatures

# degress = 2
poly = PolynomialFeatures()
poly.fit([[2,3]])

# 1(bias), 2, 3, 2**2, 2*3, 3**2
print(poly.transform([[2,3]]))
# [[1. 2. 3. 4. 6. 9.]]

